### ISSUE TITLE
Dealing with necessary SAM adapters with RxJava2.

### ISSUE THREAD

**Issue by chris-horner** [ReactiveX/RxKotlin#103]
With RxJava1, Kotlin's [automatic SAM conversion](https://kotlinlang.org/docs/reference/java-interop.html#sam-conversions) was pretty great. It let callers use syntax like:
```kotlin
Observable.zip(first, second) { a, b ->
  // Do stuff.
}
```
Unfortunately with RxJava2 Kotlin cannot work out which interface it's meant to convert, so the type must be specified explicitly with an adapter function like so:
```kotlin
Observable.zip(first, second, BiFunction<Int, Int> { a, b ->
  // Do stuff.
})
```
Is this something others care about or is it just a minor annoyance? Is it in the scope of this library to provide extension functions that provide slightly nicer Kotlin syntax?

**Comment by thomasnield** [comment]
Yes this is something that everyone is working around. I believe JetBrains acknowledged the issue but I don't know how soon a fix will happen with the compiler. 

http://stackoverflow.com/q/42635968/1373258

**Comment by chris-horner** [comment]
Some of this can be solved by creating extension functions such as
```kotlin
fun <T1, T2, R> Observable<T1>.withLatestFrom(other: ObservableSource<T2>, combiner: (T1, T2) -> R): Observable<R>
    = withLatestFrom(other, BiFunction { a, b -> combiner.invoke(a, b) })
```
I'm happy to do some legwork and get a PR up, but is it in scope? I do like how RxKotlin has become much simpler. I think the removal of factory functions was a good idea, and getting around this issue would involve making several new factory functions. Perhaps it's its own library?

**Comment by stepango** [comment]
Would be great to have this kind of extensions in rxKotlin. Feel free to make a PR.

**Comment by thomasnield** [comment]
I was thinking about this a lot today. I think it is definitely worth exploring. My recommendation is to start with only a few operators and we can play with them. If everyone feels good giving the greenlight and ensures there will be no major issues with extension function nuances, we can help implement the rest. 

I do wonder how long it will be before JetBrains resolves the issue. If it takes awhile this is probably a worthwhile effort to explore.

**Comment by thomasnield** [comment]
Feel free to put in a PR with a few common operators first. Then we will test it out and determine if it belongs in this project or a separate project.

**Comment by thomasnield** [comment]
One thing that's a shame is we cannot statically add extension functions. So we cannot fix static factories.

```kotlin
    @Test
    fun rxExtensionTest() {
        Observable.just("Alpha","Beta","Gamma","Delta","Epsilon")
                .publish()
                .autoConnect(2)
                .let {
                    Single.zip(it.count(),it.toList()) { i,list -> i to list } // compile error
                }.subscribeBy(onSuccess = ::println)
    }

    @Test
    fun rxExtensionTest2() {
        Observable.just("Alpha","Beta","Gamma","Delta","Epsilon")
                .publish()
                .autoConnect(2)
                .let {
                    it.count().zipWith(it.toList()) { i,list -> i to list } // okay
                }.subscribeBy(onSuccess = ::println)
    }

    fun <T,X,R> Single<T>.zipWith(other: Single<X>, combiner: (T,X) -> R) =
            zipWith(other, BiFunction<T,X,R> { t, x -> combiner.invoke(t,x) })
```

**Comment by thomasnield** [comment]
Ugh, this initiative is going to be a pain. Trying to fix `Single#subscribe` and I can't resolve this compile error. There is a lot of these that are going to have to be defined. If someone does it successfully, they are owed a beer. 

```kotlin
    @Test
    fun rxExtensionTest2() {
        Observable.just("Alpha","Beta","Gamma","Delta","Epsilon")
                .publish()
                .autoConnect(2)
                .let {
                    it.count().zipWith(it.toList()) { i,list -> i to list }
                }.subscribe(::println) // compile error
    }

    fun <T> Single<T>.subscribe(onSuccess: (T) -> Unit) = subscribe( Consumer { onSuccess.invoke(it) })

    fun <T,X,R> Single<T>.zipWith(other: Single<X>, combiner: (T,X) -> R) =
            zipWith(other, BiFunction<T,X,R> { t, x -> combiner.invoke(t,x) })

```

**Comment by chris-horner** [comment]
Hmm 🤔. I'm not sure it's possible to fix `Single#subscribe` given that it can take both a `Consumer` and a `BiConsumer`.

Perhaps the best approach is to introduce another extension function that aliases to `subscribe(Consumer)`. Naming that function is really challenging though. `successSubscribe`? `optimisticSubscribe`? `subscribeOrDie`? `subscribeForSuccess`?
```kotlin
fun <T> Single<T>.subscribeForSuccess(onSuccess: (T) -> Unit) = subscribe(Consumer(onSuccess))
```
I mean, you can just have a named lambda argument
```kotlin
.subscribe { result -> println(result) }
```
but it means you can't use method references. (Not to mention IntelliJ suggests you can quick-fix to a method reference when you actually can't).

**Comment by chris-horner** [comment]
I've also been thinking on how to deal with all the method overloads we need to wrap. Take `withLatestFrom()` for example. Should we provide wrappers for the calls that take one, two, three, or four arguments? If that's the case, should they be implemented as:
```kotlin
fun <T, T1, T2, R> Observable<T>.withLatestFrom(o1: ObservableSource<T1>, o2: ObservableSource<T2>, combiner: (T, T1, T2) -> R): Observable<R>
        = withLatestFrom(o1, o2, Function3(combiner))
```
or:
```kotlin
fun <T, T1, T2, R> Observable<T>.withLatestFrom(o1: ObservableSource<T1>, o2: ObservableSource<T2>, combiner: (T, T1, T2) -> R): Observable<R>
        = withLatestFrom(arrayOf(o1, o2), Functions.toFunction(combiner))
```
`Functions` is a utility class inside of RxJava's internal package so I'm hesitant to use it, however it's what the first chunk of code ultimately executes. Does anyone have thoughts on this?

**Comment by JakeWharton** [comment]
You cannot use non-public classes. They have historically and will in the
future change in backwards-incompatible ways without warning.

**Comment by thomasnield** [comment]
@chris-horner I'm not crazy about the idea to use aliases. Ideally, when JB creates a fix for this lambda inference problem, the cutover should be as simple as removing the `import` at the top of each file where these extensions are being used.

**Comment by thomasnield** [comment]
For the record, I think this is the official issue on YouTrack:
https://youtrack.jetbrains.com/issue/KT-14984

I do hope this gets fixed sometime this year. Otherwise the burden is going to be on RxKotlin to get clever with this problem.

**Comment by stepango** [comment]
As an experiment, I replaced all usages of `io.reactivex.common.functions.*` by `kotlin.jvm.functions.*` https://github.com/stepango/RxKotlin3-preview. As a result - no more SAM adapters in Kotlin code 🎉 Any feedback highly appreciated.
