### ISSUE TITLE
Add if operator

### ISSUE THREAD

**Issue by oliveiradev** [ReactiveX/RxKotlin#106]
I saw in documentation and implemented for my usage, the PR is interesting?

[If operator rxjs](http://xgrommx.github.io/rx-book/content/observable/observable_methods/if.html)

**Comment by thomasnield** [comment]
Your link seems to be broken...

**Comment by oliveiradev** [comment]
Sorry, I fix that.

**Comment by thomasnield** [comment]
Interesting. I do something like this quite a bit within a `flatMap()`, `concatMap()`, or `switchMap()` to evaluate each emission and determine what`Observable` to return.

```kotlin
  Observable.just(true, false, true).flatMap { 
            if (it) 
                Observable.range(1,5)
            else 
                Observable.empty()
        }
```

But that wasn't really too hard to do in Kotlin. Java, maybe. At that point I might as well just use the approach above.Perhaps there might be value in the factory, but I personally don't know how many folks need it. Here is another example that really isn't too bad. Kotlin makes `if` expressions pretty easy already:

```kotlin
        (if (myCondition)
            Observable.range(1,5)
        else
            Observable.empty()
        ).subscribe(::println)
```

 @stepango and @JakeWharton, what do you guys think?

**Comment by oliveiradev** [comment]
Yes @thomasnield , me too use that way, after time I create this function: 

``` kotlin 
inline fun <T> Observable<T>.ifThen(condition: Boolean, thenSource: () -> Observable<*>, 
        elseSource: () -> Observable<*>): Observable<*>
             = if (condition) thenSource() else elseSource()

**Comment by JakeWharton** [comment]
Doesn't seem related to RxKotlin since it's a new operator. Should be a proposal on RxJava.

**Comment by thomasnield** [comment]
@JakeWharton @oliveiradev I think to further clarify the scope of this project, if RxJava can effectively express the operator in Java (such as this one), then it should be proposed there first. But if RxJava cannot express it due to limitations of the Java language, then it might be candidate for RxKotlin (e.g. `Observable<Observable<T>>` extension operators like `mergeAll()`). 

So I agree with @JakeWharton  on this.

**Comment by oliveiradev** [comment]
Make sense!

**Comment by stepango** [comment]
Agreed with @JakeWharton here, useful operator in some cases but not related to rxKotlin.
