### ISSUE TITLE
Where is Callable<T>.toObservable()?

### ISSUE THREAD

**Issue by Jeevuz** [ReactiveX/RxKotlin#107]
Hi! 
I wonder why there is 
```fun <T : Any> Callable<T>.toSingle()``` and so on,
But none for regular Observable?

**Comment by stepango** [comment]
What's your use case? Since callable produce only one item only `toSingle` and `toMaybe` fits well.

**Comment by Jeevuz** [comment]
Ah, yes, you are totally right! Thanks for explanation. I was just curious. 
Dumb question closed :)
