### ISSUE TITLE
Failed to resolve: io.reactivex.rxjava:rxkotlin:x.y.z

### ISSUE THREAD

**Issue by ghost** [ReactiveX/RxKotlin#108]
Failed to resolve: io.reactivex.rxjava:rxkotlin:x.y.z
Android studio 2.3
buildToolsVersion: 25.0.2
compileSdkVersion 25

**Comment by ghost** [comment]
oh.. sorry `x.y.z`

**Comment by ghost** [comment]
Well, you need to change `x.y.z` with exact version. The latest one is `2.0.0-RC1`, so

          compile 'io.reactivex.rxjava:rxkotlin:2.0.0-RC1'

Cheers

**Comment by JakeWharton** [comment]
That's not a real version. You have to replace x.y.z with a real version.

**Comment by thomasnield** [comment]
For the record, 2.0.0 is the latest version if you are using the new io.reactivex.rxjava2 group id
