### ISSUE TITLE
Inline Completable.andThen

### ISSUE THREAD

**Issue by eygraber** [ReactiveX/RxKotlin#111]
`Completable.andThen` also gets in the way of having a nice DSL-like structure for my chains.

Something like this would help with that:

`inline fun Completable.andThen(action: () -> Completable) = andThen(action())`

**Comment by stepango** [comment]
I'm afraid this extension should have a different name because it's ambiguous what method exactly are you trying to call. 

```
Completable.andThen(CompletableSource)
``` 
Have same signature from Kotlin's perspective. Both have SAM parameter and both are transformed to `andThen(() -> T)`

Do you have a different name in mind?

**Comment by eygraber** [comment]
I have them both in a project, and there's no ambiguity. Am I missing something?

**Comment by stepango** [comment]
Let me give you an example.
1. Let's add your extension to a project
`inline fun Completable.andThen(action: () -> Completable) = andThen(action())`
2. Let's call `Completable.complete().andThen { Completable.complete() }` in some random file

@eygraber what method would be called?

**Comment by eygraber** [comment]
@stepango I was using rxjava 1 🙈

**Comment by thomasnield** [comment]
We can put something towards the 1.x branch if you want

**Comment by eygraber** [comment]
@thomasnield that might be helpful in general, but I've moved on to rxjava 2 already 😁

**Comment by thomasnield** [comment]
Fair enough
