### ISSUE TITLE
Call the named arguments for lambda Subscribers within subscribeBy method

### ISSUE THREAD

**Issue by elton2048** [ReactiveX/RxKotlin#113]
In using RxJava 2.x it is possible to call the override function within the subscribe method

```kotlin
observableFunction.subscribe(object : Observer<T> {
    override fun onNext(t: T?) {
        println("onNext")

        // Do the task in onComplete function
        onComplete()
    }

    override fun onComplete() {
        // Task after received the onComplete() call
        println("onComplete after onNext")
    }

    override fun onSubscribe(d: Disposable?) {}

    override fun onError(e: Throwable?) {}
})
```

In RxKotlin the subscribeBy method can name the lambda Subscribers for better readability with lesser code. Yet is it possible to call the function within the subscribeBy method?

```kotlin
observableFunction.subscribeBy( 
    onNext = { status ->
        println("onNext")

        // Do the task in onComplete function
        // Solution??
    },  
    onError = {},
    onComplete = {
        // Task after received the onComplete() call
        println("onComplete after onNext")
    }
)
```

**Comment by stepango** [comment]
```
observableFunction.subscribeBy( 
    onNext = { status ->
        println("onNext")

        // Do the task in onComplete function
        onComplete()
    },  
    onError = {},
    onComplete = ::onComplete
)

fun onComplete() = println("onComplete after onNext")
```
Why you could ever need to call `onComplete` twice?

**Comment by DasBonkers** [comment]
I think it's more of a generic question rather than that he needs twice.

**Comment by thomasnield** [comment]
@elton2048 you should let RxJava call `onComplete` for you once the sequence terminates. There is absolutely no reason you should ever have to call it from `onNext`. Do you need some resources to demystify RxJava events? I can provide some...

**Comment by elton2048** [comment]
@thomasnield You are right. The `onComplete`  call should be called in the function if using create() method to build Observable but not in the subscribe function. Thanks for that.
