### ISSUE TITLE
Updating snippet on main page

### ISSUE THREAD

**Issue by hughesadam87** [ReactiveX/RxKotlin#117]
Hi,

I spent about 25 min trying to debug why I couldn't get rxkotlin working, only to realize that when I added rxkotlin as an external jar directly to my project, the import syntax is,

    import io.reactivex.rxkotlin.toObservable

Instead of

    import rx.Observable

as shown in the main page code snippet.   Is the snipped out of date, or am I simply doing something wrong?

**Comment by thomasnield** [comment]
Yes, that was from RxKotlin 1.0. I just updated the README for RxKotlin 2.0 with the obsolete code you kindly pointed out. Thank you.

**Comment by hughesadam87** [comment]
TY
