### ISSUE TITLE
Change Implementation of Disposable.addTo to use DisposableContainer

### ISSUE THREAD

**Issue by RoryKelly** [ReactiveX/RxKotlin#127]
Change implementation of 
```
fun Disposable.addTo(compositeDisposable: CompositeDisposable): Disposable

```
to

```
fun Disposable.addTo(compositeDisposable: DisposableContainer): Disposable
``` 

This would enable the use of custom `DisposableContainer`s. The current implementation limits use to `CompositeDisposeable`s.

For example, on Android it is possible to build a `DisposableContainer` that auto-disposes based on the Android lifecycle. However it is not possible to use `observable.addTo(myCustomDisposeable)`

**Comment by JakeWharton** [comment]
This would be a binary incompatible change and it's a non-public API. You
can add this function to your own codebase where the use of internal APIs
is much easier to manage. As a library this project cannot use internal
APIs.

**Comment by RoryKelly** [comment]
Sorry this is probably a dumb question, I don't understand where am I using a non public api?

`public interface DisposableContainer {...}`

or 

`fun Disposable.addTo(compositeDisposable: CompositeDisposable): Disposable `

Are you talking about the Android Lifecycle functions? I'm talking about the new `android.arch.lifecycle` package and `LifecycleObserver`/`LifecycleRegistry` which are public classes.

**Comment by JakeWharton** [comment]
DisposableContainer is not an RxJava public API

**Comment by RoryKelly** [comment]
Just noticed it's in the `io.reactivex.internal` package. I'm guessing that's why it's non public, closing the issue and pull request.

**Comment by thomasnield** [comment]
Thanks @JakeWharton
