### ISSUE TITLE
RxKotlin is using RxJava 2.1.0 when 2.1.1 is out

### ISSUE THREAD

**Issue by priyankvex** [ReactiveX/RxKotlin#136]
In RxAndroid I see this commment
```
// Because RxAndroid releases are few and far between, it is recommended you also
// explicitly depend on RxJava's latest version for bug fixes and new features
```
Why was this not done with RxKotlin?

**Comment by thomasnield** [comment]
This wasn't documented explicitly for RxKotlin, but we follow the same policy.

**Comment by priyankvex** [comment]
But I can't swap in the latest RxJava version I guess. Will have to wait for new RxKotlin release.

**Comment by thomasnield** [comment]
I am confused... can you not just specify the RxJava dependency you want on Gradle/Maven?

**Comment by thomasnield** [comment]
From my experience, the specified version of RxJava will be chosen (and override RxKotlin's) if you just explicitly specify it like this in Gradle/Maven:

```groovy
dependencies {
    compile 'io.reactivex.rxjava2:rxjava:2.1.1'
    compile 'io.reactivex.rxjava2:rxkotlin:2.1.0'
}
```

**Comment by priyankvex** [comment]
I had that in mind, but defining RxJava version externally was not in the docs, so was wondering will it cause any side-effects. Sorry. :slightly_smiling_face:

**Comment by thomasnield** [comment]
No worries, that's a valid concern. Ill document that later.
