### ISSUE TITLE
Cool disposable pattern

### ISSUE THREAD

**Issue by ZakTaccardi** [ReactiveX/RxKotlin#137]
Saw someone do this, thought it was pretty cool, and no need to operator overload.

```
// Kotlin's extension methods can provide syntactic sugar
   fun Disposable.into(disposables: CompositeDisposable) {
   disposables.add(this)
  }

  myObservable.subscribe()
       .into(disposables)
```

Maybe something like this should be an RxKotlin pattern? /discuss

**Comment by thomasnield** [comment]
We already have an `addTo()` I think that does this. If not, yes it should be added.

**Comment by thomasnield** [comment]
Just confirmed we do have this with the `addTo()` function. I'm going to close, but feel free to open again if I'm missing anything.
