### ISSUE TITLE
Remove T.toMaybe(), T.toSingle()

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxKotlin#144]
We really should remove the following extensions: 

https://github.com/ReactiveX/RxKotlin/blob/2.x/src/main/kotlin/io/reactivex/rxkotlin/single.kt#L9
https://github.com/ReactiveX/RxKotlin/blob/2.x/src/main/kotlin/io/reactivex/rxkotlin/maybe.kt#L9

I'm finding these quickly clash with other libraries and domains that have specialized types with good reason to have `toSingle()` and `toMaybe()`. For instance, a JavaFX popup `Dialog` could be extended to return a `Maybe` emitting the users response. A `toMaybe()` would be the natural name for this but it clashes with RxKotlin, and it is definitely clashing with [RxKotlinFX](https://github.com/thomasnield/RxKotlinFX).

Therefore, let's remove any extension functions targeting a general, single `T` type.

**Comment by OrdonTeam** [comment]
These extensions also collide in such case:
```
val toMaybe1: Maybe<Unit> = Single.just(Unit).toMaybe()
val toMaybe2: Maybe<Observable<Unit>> = Observable.just(Unit).toMaybe()
```

**Comment by thomasnield** [comment]
I'm following up on this stuff this weekend

**Comment by onelaview** [comment]
It seems these 2 following extensions collide with each other.

```
fun <T : Any> T?.toMaybe(): Maybe<T> = Maybe.create { s -> if (this != null) s.onSuccess(this); s.onComplete() }
fun <T : Any> (() -> T).toMaybe(): Maybe<T> = Maybe.fromCallable(this)
```

I'm unable to use the latter to apply `.toMaybe()` to a **lambda** so that it is the same as calling `Maybe.fromCallable(lambda)`. Compiler always resolves it to the former extension.

```
val myInt: Int? = null
{ myInt }.toMaybe() // compiler resolves this to use the former extension function
                    // i.e. it produces Maybe<() -> Int?>
```

**Comment by thomasnield** [comment]
Yes, they both need to go away, all `toMaybe()` and `toSingle()` extensions.

**Comment by alexbirkett** [comment]
😭 I loved `.toSingle()`

**Comment by thomasnield** [comment]
@alexbirkett you can always implement it on your own domain. These extensions were highly problematic and clashed with other libraries that put toMaybe() and toSingle() on specific types.
