### ISSUE TITLE
Major Release

### ISSUE THREAD

**Issue by MarioAriasC** [ReactiveX/RxKotlin#15]
The Kotlin community has been working in a proper release for RxKotlin 

@benjchristensen Which steps we need to take to create release?

**Comment by benjchristensen** [comment]
We can copy over the new build/release config from RxJava in these locations:
- https://github.com/ReactiveX/RxJava/tree/1.x/gradle
- https://github.com/ReactiveX/RxJava/blob/1.x/.travis.yml

Then I can update the .travis.yml file with the encrypted credentials for Bintray and Sonatype. Then you can build and release just via git tags via Travis.

**Comment by benjchristensen** [comment]
I think it's ready to go. Let me know when the code is ready to release and I can do the first one so I can debug through any issues. 

What version number do you want for this, 1.0.0?

**Comment by MarioAriasC** [comment]
@benjchristensen Thanks for the info, let me discuss it with the community 

@cy6erGn0m @orangy @abreslav @hhariri do we want this to version 1.0.0? Probably we want something to said that is compatible with version M11 and so on

**Comment by orangy** [comment]
What is current version of RxJava? We probably want major/minor to match RxJava, and then use 3rd number to reflect Kotlin Milestone. E.g. if RxJava is 1.5, for M11 it would be 1.5.11

**Comment by benjchristensen** [comment]
RxJava is at 1.0.8: https://github.com/ReactiveX/RxJava/releases

**Comment by benjchristensen** [comment]
Trying to track the RxJava version would be difficult to do reliably as every patch release would require a release of RxKotlin. Also, that approach would fall apart the first time you need to release without RxJava having released. Or if you need to do a breaking change that bumps RxKotlin to 2.0. 

The various projects are decoupled so they can have different lifecycles.

**Comment by orangy** [comment]
I see, makes sense. Then probably keep it at 0.11.\* for M11, and when Kotlin releases, bump to 1.0?

**Comment by MarioAriasC** [comment]
The most reasonable solution is to use kotlin versions, so 0.11 for this release and so on

**Comment by cy6erGn0m** [comment]
@MarioAriasC @benjchristensen So do you have idea when could it be released?

**Comment by benjchristensen** [comment]
A release can go whenever wanted. @MarioAriasC should have the ability already. Just let me know if there is something not working or needing guidance if it is unclear. 

Anyone with commit privileges can tag the branch and it will trigger a build and release. The version for the file and Maven Central is the Git tag name. 

![screen shot 2015-05-06 at 12 43 12 pm](https://cloud.githubusercontent.com/assets/813492/7502007/a0225188-f3ed-11e4-97a5-014910e2d249.png)

**Comment by MarioAriasC** [comment]
@benjchristensen If we want to use Kotlin versions, in this case 0.11 or M11, 0.11 will be considered and older version compared to 0.21.0? Better if we use M11?

Thanks

**Comment by cy6erGn0m** [comment]
@MarioAriasC @benjchristensen  What about 0.22.11 ?

**Comment by MarioAriasC** [comment]
@cy6erGn0m @benjchristensen sounds good

**Comment by MarioAriasC** [comment]
I create this release https://github.com/ReactiveX/RxKotlin/releases/tag/v0.22.11 
I don't know if I made it right. 

@benjchristensen Could you confirm me?

**Comment by cy6erGn0m** [comment]
@MarioAriasC @benjchristensen It doesn't work: no release actually done

**Comment by orangy** [comment]
I wonder if we can speed things up a little bit. If you don't have time/priority for releasing compatible Kotlin bindings for Rx, is it possible we can do it?

**Comment by benjchristensen** [comment]
You can look at the build information on Travis to see the issue. It failed with a branch config issue.

https://travis-ci.org/ReactiveX/RxKotlin/builds/64004943

Trying to resolve.

**Comment by benjchristensen** [comment]
I added the necessary config to build.gradle and now the release works fine the way you did it. I deleted and re-added the tag to release. 

Build: https://travis-ci.org/ReactiveX/RxKotlin/builds/65133450
Bintray: https://bintray.com/reactivex/RxJava/RxKotlin/0.22.11/view
Maven Sync: https://bintray.com/reactivex/RxJava/RxKotlin/0.22.11/view#central

**Comment by MarioAriasC** [comment]
Done
