### ISSUE TITLE
Subscribing to Observables with Optionals

### ISSUE THREAD

**Issue by vander2675** [ReactiveX/RxKotlin#157]
Hello 
Currently I can't subscribe an ```Observable<String?>``` to an ```BehaviorObject<String?>```.
Neither can I subscribe an ```Observable<String>```to an ```BehaviorObject<String?>```

Coming from RxSwift both of these options seem reasonable for me. Is there any reason for this behavior?

**Comment by thomasnield** [comment]
Yes, RxJava2 does not support emitting null values and will immediately throw errors if it encounters them. 

This means nullable types in Kotlin cannot be used as emissions, and you have to resort to Java 8 or Guava Optionals, or other wrappers for null values. 

The only way this will be fixed is for a reactive implementation to be built in Kotlin from scratch, which [is an ongoing discussion](https://github.com/reactor/reactor-core/issues/979#issuecomment-350744025).

**Comment by stepango** [comment]
Consider using `Observable<Optional<String>>` for this kind of cases.
