### ISSUE TITLE
Bad release 2.1.0 comment

### ISSUE THREAD

**Issue by danielgomezrico** [ReactiveX/RxKotlin#158]
Hi

In https://github.com/ReactiveX/RxKotlin/releases/tag/2.1.0 you see "Kotlin 1.3.0" but that version of Kotlin doesnt exists.

Did you mean "Kotlin 1.2.0" ?

**Comment by thomasnield** [comment]
It is not tied to the Kotlin version. It has its own version numbering system loosely tied to RxJava.

**Comment by thomasnield** [comment]
Oh sorry I misunderstood. I'll take a look later.

**Comment by danielgomezrico** [comment]
@thomasnield what do you mean by "It has its own version numbering system loosely tied to RxJava" ?

**Comment by thomasnield** [comment]
@caipivara I fixed the description. RxKotlin 2.x corresponds to RxJava 2.x, but the `x` is not synchronized.
