### ISSUE TITLE
ofType allows to filter any type

### ISSUE THREAD

**Issue by davidkraus** [ReactiveX/RxKotlin#166]
Hey, i just had a strange bug where my streams just returned nothing. See following code example:

```
    data class Result<out T>(val data: T)

    open class Data {}
    class DataA : Data() {}
    class DataB : Data() {}

    val actions = Observable.just(Result(DataA()), Result(DataB()))
    // missing map from result to data

    actions.ofType<DataB>().blockingFirst()
```
I missed to map from result to data but it compiles perfectly fine but breaks at runtime (blockingFirst never gets to see an event).
I think this is because the ofType Observable has no type restrictions: 

`inline fun <reified R : Any> Observable<*>.ofType(): Observable<R> = ofType(R::class.java)`

i forked the repo and changed this to (`in R` instead of `*`):

`inline fun <reified R : Any> Observable<in R>.ofType(): Observable<R> = ofType(R::class.java)`

This works for my case and yields a compiler error, but the last test now also yields a compiler error:
```
        source.ofType<Comparable<*>>()
                .test()
                .await()
                .assertValues(BigDecimal.valueOf(15, 1), 2, BigDecimal.valueOf(42), 15)
                .assertNoErrors()
                .assertComplete()
```
This is because `source` is of type `Number` which does not confirm to the Comparable interface.

Is this the desired behavior of ofType? I would assume otherwise since this is not possible with the ofType from RxJava.

**Comment by JakeWharton** [comment]
This is definitely possible with plain RxJava and is the intended behavior of this RxKotlin operator.

**Comment by davidkraus** [comment]
Jep, you are right - also works in java. I think i had a litte bit a misconception of what ofType should do. 
But thanks to Kotlin i can just define a additional function that does the job. Just not sure about the name though, `ofSubType`, `ofTypeStrict`, `filterByType` ...

Thanks for the fast response
