### ISSUE TITLE
Add filterNotNull extension

### ISSUE THREAD

**Issue by imanushin** [ReactiveX/RxKotlin#172]
Add method the same with in kotlin documentation - https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/filter-not-null.html

```
fun <T : Any> Observable<T?>.filterNotNull(): Observable<T> (source)
```

implementation is simple: 

```
fun <T : Any> Observable<T?>.filterNotNull(): Observable<T> (source) =
        filter { it != null }
        .map { it as T }
```

**Comment by JakeWharton** [comment]
The map is wasteful to append since it's only to appease the type system.
An unsafe cast on the filter is enough.

**Comment by imanushin** [comment]
@JakeWharton , I found, that nulls are forbidden in the RX Java. Will close issue
