### ISSUE TITLE
repeatWhen not working in rxkotlin 2.2.0

### ISSUE THREAD

**Issue by davidgodzsak** [ReactiveX/RxKotlin#177]
I try to make this code repeat forever and print the range just for a test:

```kotlin
import io.reactivex.Observable
import java.util.concurrent.TimeUnit


fun range(): Observable<Int> = Observable.range(1, 5)

fun poll(): Observable<Int> =
        range().doOnComplete { println("range completed") }.repeatWhen { completed ->
            completed
                    .delay(1, TimeUnit.SECONDS)
                    .doOnNext { println("next") }
                    .doOnError { println("error") }
                    .doOnComplete { println("completed") }
        }

fun main(args: Array<String>) {
    poll().subscribe(
            { println(it) },
            { println("error in poll") },
            { println("poll completed") })
}
```

The program stops with exit code 0 and the output is, while it should not stop at all:

```
1
2
3
4
5
range completed
```

Am I doing something wrong, or is this a bug?

**Comment by akarnokd** [comment]
RxJava Schedulers use daemon threads so your application quits once the first range has been emitted. Use `Thread.sleep(10000)` to see there is repetition.

**Comment by davidgodzsak** [comment]
Oh I get it. But how do I make this loop forever in a reasonable way? I mean I don't think it is a nice solution to put it in a while(true){} loop, or Thread.sleep(1000000000000), etc.

**Comment by akarnokd** [comment]
You have to block the main thread by some means.
