### ISSUE TITLE
Should there be advertisements in the README for paid books?

### ISSUE THREAD

**Issue by TrevorSStone** [ReactiveX/RxKotlin#178]
The current README has two paid books listed even before how you would include RxKotlin in a project.

This feels like not the right place to put these (if they should be listed in this repo at all)

A wiki or footnote at the end of the README feels like a much more appropriate place for these to be listed if they are truly adding value by being mentioned.

![image](https://user-images.githubusercontent.com/2424354/39378353-02b2ab36-4a0d-11e8-86b1-a9a7806e001d.png)

**Comment by kles4enko** [comment]
Just check books author and person name who added these lines to the README...  Fun (not).

**Comment by DrewCarlson** [comment]
@kles4enko I really was not expecting that..

For reference, this is the pull request for it: https://github.com/ReactiveX/RxKotlin/pull/154

Merged the same day with no conversation at all.  Seems odd to me that it was even considered.  People will take that section as a formal recommendation for those books which is an obvious problem for so many reasons.

At the very least turning it into a footnote with a disclaimer about not being officially supported or vetted would be the right thing to do.

**Comment by thomasnield** [comment]
Guys, I want to say book authors make so little on royalties it's rarely done for the money. We write them to help the community and legitimize a technology via a publisher, because we are passionate about the topic and the OSS work we contribute.

**Comment by thomasnield** [comment]
If you want to move the books to the bottom of the page, feel free to put in a PR.
