### ISSUE TITLE
Library has an unsupported format

### ISSUE THREAD

**Issue by damianpetla** [ReactiveX/RxKotlin#18]
I have added this library version 0.21.0 to my project. Now when I open any class I have attached message on top of the editor
![screenshot 2015-03-27 11 13 27](https://cloud.githubusercontent.com/assets/8932745/6865849/7cd65520-d472-11e4-84e2-969b17e934a3.png)

I am using Android Studio 1.1.0 and Kotlin plugin 0.11.91

**Comment by MarioAriasC** [comment]
We're working on that

Meanwhile you could build it form source and will work

**Comment by ScottPierce** [comment]
Is there an ETA on this?

**Comment by MarioAriasC** [comment]
You could follow this task  https://github.com/ReactiveX/RxKotlin/issues/15

In theory everything is ready, but for some reason isn't being published.

Now we'll update to M12

**Comment by MarioAriasC** [comment]
Done and with M12 compatibility
