### ISSUE TITLE
Simple extension functions for combining Observables

### ISSUE THREAD

**Issue by aballano** [ReactiveX/RxKotlin#182]
Hi there, what do you think about adding this two extension functions for `Observable`?

```
/** o1 + o2 === Observable.concat(o1, o2) */
operator fun <T> ObservableSource<out T>.plus(other: ObservableSource<out T>): Observable<T> =
      Observable.concat(this, other)
```

```
/** o1 and o2 === Observable.merge(o1, o2) */
infix fun <T> ObservableSource<out T>.and(other: ObservableSource<out T>): Observable<T> =
      Observable.merge(this, other)
```

Would they make sense? If so I could create a PR adding them :)

**Comment by thomasnield** [comment]
I'm going to vote negative on this one. Not just because it looks weird, but because Observables/Flowables/Singles/Maybes are often used with a fluent style with chained calls, not one-step operator `+-*/` calls.

**Comment by aballano** [comment]
I'm closing this then, thanks for the feedback!

FYI I included them into our project but renamed so they're more explicit

```
infix fun <T> ObservableSource<out T>.concat(other: ObservableSource<out T>): Observable<T> =
      Observable.concat(this, other)

infix fun <T> ObservableSource<out T>.merge(other: ObservableSource<out T>): Observable<T> =
      Observable.merge(this, other)
```

And for the shake of context, my usecase: 

```
presenter.observeViewEvents(
    initEvent.toObservable() merge cardClicked()
).subscribeBy(...)
```

**Comment by thomasnield** [comment]
Yeah we learned quickly in this project that some things implement should be on one's personal domain, not necessarily in a public library.
