### ISSUE TITLE
Update Kotlin & RxJava versions

### ISSUE THREAD

**Issue by ashishkrishnan** [ReactiveX/RxKotlin#183]
The project currently uses Kotlin 1.1.60 and RxJava 2.1.6.

Can we bump to the latest version or the most the stable of these dependencies? Trying to understand the rationale behind this.

Also, is this PR welcome?

**Comment by JakeWharton** [comment]
If you update them, by the time there's a new release they'll probably both be out of date again. This project rarely releases. Also the versions are forward compatible so it really doesn't matter. People who care about what version of Kotlin and RxJava they're using are specifying dependencies on them to ensure the new version is used. It's infeasible for every library to release every time a dependency has a new version.

**Comment by ashishkrishnan** [comment]
Does makes sense. @JakeWharton Anyways, major upgrades to the dependencies should be pulled in to get all the upstream bugfixes. Also, agreed with you on infeasibility of the maintainers to upgrade every single update.

**Comment by ashishkrishnan** [comment]
So, using the latest version of a dependency should override the version specified in this project. Right?

**Comment by JakeWharton** [comment]
Yes
