### ISSUE TITLE
No zero-arg flatMapIterable()

### ISSUE THREAD

**Issue by bemusementpark** [ReactiveX/RxKotlin#186]
It would be useful to have a zero-arg `flatMapIterable`.

given:
```
val observable: Observable<Iterable<T>>
```

Currently we would need to flat map using a lamda or the `identity()` function.
```
observable.flatMapIterable { it }.subscribe()
observable.flatMapIterable(identity()).subscribe()
```

Although it would be convenient if this were not necessary and we could instead call:

```
observable.flatMapIterable().subscribe()
```

on any `Observable<Iterable<T>>`

Implemented [here](https://github.com/ReactiveX/RxKotlin/pull/185)

**Comment by joshfriend** [comment]
@stepango I think you can close this now that the PR is merged
