### ISSUE TITLE
Another useful function ?

### ISSUE THREAD

**Issue by tbruyelle** [ReactiveX/RxKotlin#19]
When you want to use RX with a external lib that doesn't use RX, you need to wrap the library call with

``` kotlin
Observable.defer { Observable.just { lib.method() }}
```

I think it may be useful to have a function for that. I tried to write the following, but it doesn't compile and I didn't find why.

``` kotlin
fun <T> rxify(body: () -> T): Observable<T> = Observable.defer(Observable.just(body))
```

Do you think it's relevant and if yes can you help me write it correctly :P (I'm a kotlin noob) ?

**Comment by tbruyelle** [comment]
I think I found how to write this correctly : 

``` kotlin
fun <T> rxify(body: () -> T): Observable<T> = Observable.defer({ Observable.just(body()) })
```

(I know the function name is terrible ^^)

**Comment by jmfayard** [comment]
I would have say 

``` kt
Observable<String>.from {
     "Helllo World!"
}

fun <T> Observable<T>.from(body: () -> T): Observable<T> =
        Observable.defer { Observable.just(body()) }
```

But I have an error `cannot access init, it is package * protected in Observable`

**Comment by cy6erGn0m** [comment]
It looks like you need

``` kotlin
fun <T> singleObservable(supplier: () -> T): Observable<T> =
        deferredObservable { supplier().toSingletonObservable() }
```

Btw I am not sure if it common enough to include it into the library

**Comment by PaulWoitaschek** [comment]
With the latest releases of RxJava I think this can be closed. You can just use

``` kotlin
Observable.fromCallable { lib.method() }
```
