### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by vee-zhang** [ReactiveX/RxKotlin#192]
## en......two picture:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/21964085/43037424-8260a44e-8d3f-11e8-9956-8fdc410d78a8.png">
<img width="709" alt="image" src="https://user-images.githubusercontent.com/21964085/43037454-afd8a8ea-8d3f-11e8-9940-d4a7f4c0dd6b.png">

why???

**Comment by thomasnield** [comment]
I'm not quite sure I understand the question. Why the compile error?

**Comment by thomasnield** [comment]
It's probably expecting an `Observable` instead of a `Single`, since that second example is dealing with an `Observable` chain.

**Comment by QiuChenly** [comment]
有丶东西
这不是Single吗  Observable是什么鬼

**Comment by chris-hatton** [comment]
Even though you have used 'Observable.just(...)' to emit a single value, that result is still formally an 'Observable' which has a different API to 'Single'. Do not expect to mix both types interchangeably.

即使您使用'Observable.just（...）'来发出单个值，该结果仍然是正式的'Observable'，其具有与'Single'不同的API。 不要指望两种类型可以互换。
