### ISSUE TITLE
Placement of badges for Build and Maven Central

### ISSUE THREAD

**Issue by Mikerr1111** [ReactiveX/RxKotlin#194]
I noticed the placement of the build & maven central badges were not placed on the top of the Readme file like they are in the RxJava readme file. I was wondering if that was intended?

RxKotlin
![rxkotlin](https://user-images.githubusercontent.com/18353476/43286374-a8b87c9e-90d6-11e8-810e-a44f9be8dd3f.png)

RxJava
![rxjava](https://user-images.githubusercontent.com/18353476/43286376-aa40cec2-90d6-11e8-8b62-48d875303391.png)

**Comment by Mikerr1111** [comment]
Now that you say it that does make sense for mobile. I just rarely see it.

**Comment by JakeWharton** [comment]
Woo! I'm slowly converting the world over!

(I don't even remember if I was involved in the argument for their positioning on this project or not.)

**Comment by thomasnield** [comment]
We break conventions. That's how we roll. (with Jake Wharton's blessing, of course). 

In all seriousness, I agree with Jake. To add, I found a well-summarized code example at the top shows the intent of the library.
