### ISSUE TITLE
ERROR: Cannot set property 'defaultVersionStrategy' on null object

### ISSUE THREAD

**Issue by TomatoWithEgg** [ReactiveX/RxKotlin#215]
I'm cloning this library open in my Android Studio 3.4.but make a mistake when building.This is mistake info:
* What went wrong:
A problem occurred evaluating root project 'rxkotlin'.
> Failed to apply plugin [class 'nebula.plugin.rxjavaproject.RxJavaReleasePlugin']
   > Cannot set property 'defaultVersionStrategy' on null object

**Comment by vpriscan** [comment]
@TomatoWithEgg RxKotlin 2.4.0-beta.1 has just been released and this Nebula plugin which was causing problems has been removed. This issue should now be resolved. Please try the new version and give a feedback.

**Comment by TomatoWithEgg** [comment]
Thank you, this issue can be closed.
