### ISSUE TITLE
Admin Help - Adding a Collaborator

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxKotlin#217]
ReactiveX admins, @akarnokd,

What channel do I go through to add a collaborator for a ReactiveX project? I want to make [Vedra](https://github.com/vpriscan) a collaborator for RxKotlin.

**Comment by akarnokd** [comment]
I have to find some of the owners of ReactiveX and ask for permission. Let me check.

**Comment by akarnokd** [comment]
Apparently, I can add labels but I don't have access to the settings tab here.

**Comment by thomasnield** [comment]
@akarnokd me neither. Please let me know if you get any info on that. I can contact them directly if I get an email or handle.

**Comment by akarnokd** [comment]
I granted you Admin privileges too @thomasnield . Looks like @stepango could have done it too.

**Comment by thomasnield** [comment]
@akarnokd thanks!
