### ISSUE TITLE
RxKotlin library, 0.22.12, is not compatible with new Kotlin M13 release.

### ISSUE THREAD

**Issue by gsusie** [ReactiveX/RxKotlin#22]
Currently using this library within Android Studio 1.3.x and just updated AS Kotlin plugins to M13 (0.13.1513). Gradle build error states that this library, RxKotlin-0.22.12.jar and funktionale-0.5.1d_M12.jar have unsupported formats. Any plans to update soon? Is there an ETA? Thank you.

**Comment by JakeWharton** [comment]
Feel free to send a PR

**Comment by MarioAriasC** [comment]
Next weekend

**Comment by MarioAriasC** [comment]
Use 0.22.13
