### ISSUE TITLE
RxJava 3 support

### ISSUE THREAD

**Issue by cesards** [ReactiveX/RxKotlin#224]
Hey guys, is there any plan to support RxJava 3?

I cloned the project and tried to compile the project with the RxJava 3-RC4 dependency but for some reason, my AS is not able to find an NDK dependency or tool the project needs, so I can't figure out what's going on.

**Comment by vpriscan** [comment]
Hello, support will be added soon.

**Comment by vpriscan** [comment]
@cesards RxKotlin 3.0.0-RC1 targeting RxJava 3.0.0-RC9 has been released.
https://github.com/ReactiveX/RxKotlin/releases/tag/3.0.0-RC1

**Comment by cesards** [comment]
Amazing! Thanks ❤️

**Comment by adenisyuk** [comment]
Thanks for your efforts.
Do you have any plans to release RxKotlin 3.0.0 targeting RxJava 3 (version 3.0.0) ?

**Comment by vpriscan** [comment]
@adenisyuk yes, in a few days, after #227 is discussed.

**Comment by vpriscan** [comment]
RxKotlin 3.0.0 targeting RxJava 3.0.0 is now released.
https://github.com/ReactiveX/RxKotlin/releases/tag/3.0.0
