### ISSUE TITLE
zipWith and Kotlin 1.4.0

### ISSUE THREAD

**Issue by BraisGabin** [ReactiveX/RxKotlin#236]
After I update to Kotlin 1.4.0 I'm getting this warning where I use `io.reactivex.rxjava3.kotlin.zipWith`:

```
w: /Users/brais.gabin/projects/XXXXX/Class.kt: (79, 8): Candidate resolution will be changed soon, please use fully qualified name to invoke the following closer candidate explicitly '
public final fun <U : Any!, R : Any!> zipWith(other: SingleSource<U!>!, zipper: BiFunction<in UserProfileResponseDTO!, in U!, out R!>!): Single<R!>! defined in io.reactivex.rxjava3.core.Single'
```

**Comment by vpriscan** [comment]
@BraisGabin 
this is handled in _3.x-new-type-inference_ branch, will merge soon to 3.x

**Comment by mabae** [comment]
The branch seems to be merged. Is there an expected release date?

**Comment by vpriscan** [comment]
RxKotlin 3.0.1 has been released. SAM helper functions have been deprecated, they are made obsolete with new type inference algorithm in Kotlin 1.4. 
_io.reactivex.rxjava3.kotlin.zipWith_ has been deprecated in favour of _io.reactivex.rxjava3.core.Single#zipWith_.

**Comment by BraisGabin** [comment]
Then, we can close this.
