### ISSUE TITLE
extensions for coroutine flow

### ISSUE THREAD

**Issue by rouddy** [ReactiveX/RxKotlin#256]
Now, Kotlin supports [coroutine flow](https://kotlinlang.org/docs/flow.html), similar to ReactorX.

However, there are no useful operators like onErrorResume, groupBy, and so on.

There is a way to convert an observable to a flow and vice versa, but RxKotlin can provide operators.

In the Dart language, there is a stream as a basic class, and [RxDart](https://pub.dev/packages/rxdart) enables the use of operators with streams.

Is there any chance that RxKotlin will provide an extension for coroutines?

**Comment by akarnokd** [comment]
There are official interop utilities for RxJava 2 and RxJava 3 provided by Kotlin itself: 

https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-rx3/

You should be able to convert back-and-forth and use RxKotlin methods while in Rx land.

**Comment by rouddy** [comment]
I understood as no.
thanx for the answer.
