### ISSUE TITLE
Using new intellij EAP 143.379 EAP with kotlin 1.0.0-beta-1038

### ISSUE THREAD

**Issue by fatlazycat** [ReactiveX/RxKotlin#28]
Get rxkotlin-0.22.14.jar has an unsupported format.

Needs a new release ?

Thanks

**Comment by MarioAriasC** [comment]
Every kotlin library needs new releases until we get stable ABI

RxKotlin for 1.0 Beta will be released a couple of days after the official Kotlin 1.0 Beta release

**Comment by fatlazycat** [comment]
Thanks
