### ISSUE TITLE
Recompile for RC

### ISSUE THREAD

**Issue by ScottPierce** [ReactiveX/RxKotlin#43]
As I'm sure you know, RC requires that all kotlin code be recompiled. I'm seeing an error when using the current version of rxkotlin:

> Kotlin library 'rxkotlin-0.30.1.jar' has an unsupported format. Please update the library or the plugin. 

I saw there were already some commits around the RC release a few hours ago. I just wanted to create this to track the RC release update.

http://blog.jetbrains.com/kotlin/2016/02/kotlin-1-0-release-candidate-is-out/#more-3453

**Comment by JakeWharton** [comment]
Use version 0.40.1

**Comment by ScottPierce** [comment]
Thanks for the update :-) :+1:
