### ISSUE TITLE
Recompile RxKotlin using the Kotlin RC 1.0 candidate.

### ISSUE THREAD

**Issue by carlbenson** [ReactiveX/RxKotlin#44]
Libraries compiled with Kotlin betas are incompatible with code compiled with Kotlin RC.
Thanks.

**Comment by MarioAriasC** [comment]
Already resolved 

https://github.com/ReactiveX/RxKotlin/releases/tag/v0.40.1

**Comment by carlbenson** [comment]
Great, didn't realise. Thanks!
