### ISSUE TITLE
Needs rebuild for 1.0?

### ISSUE THREAD

**Issue by mikehearn** [ReactiveX/RxKotlin#51]
Hiya, could you rebuild for 1.0 and maybe sync the version number with RxJava? It briefly confused me that the version number wasn't listed anywhere, and yet wasn't the same as RxJava.

**Comment by MarioAriasC** [comment]
We're working on that, Travis is being a bad boy in the last week.

But the code as is on branch 0.x will work with Kotlin 1.0 and RxJava 1.1.1 if you want to build it for your self.

We'll publish a proper 1.0 version next week

**Comment by mikehearn** [comment]
thanks!

**Comment by MarioAriasC** [comment]
Sorted, checkout version 0.55.0 https://github.com/ReactiveX/RxKotlin/releases/tag/v0.55.0
