### ISSUE TITLE
Could not find 0.50 release

### ISSUE THREAD

**Issue by rshah** [ReactiveX/RxKotlin#54]
I could not find 0.50 in bintray or maven repo.
Could you please update the repo with this release?
Thank you.

**Comment by MarioAriasC** [comment]
We're having problems with our build infrastructure, we're working on that
Meanwhile you could try this one

https://jitpack.io/#reactivex/rxkotlin/v0.50

**Comment by rshah** [comment]
Thank you. I'm using it now.

**Comment by cy6erGn0m** [comment]
@MarioAriasC any updates on this? users still can't use 0.50 neither via central nor jcenter

**Comment by MarioAriasC** [comment]
Sorted https://github.com/ReactiveX/RxKotlin/releases/tag/v0.55.0
