### ISSUE TITLE
RxJavaMath extensions

### ISSUE THREAD

**Issue by maxandron** [ReactiveX/RxKotlin#55]
Hi,

I really dislike the RxJavaMath library because it requires me to wrap my existing observables.
With Kotlin we can easily do this with extension methods.

With your permission, would love to add it to the library. This will entail a new RxJavaMath dependency though.

What do you think?

**Comment by JakeWharton** [comment]
To avoid putting the dependency on everyone using this library, it would
have to be another module under the RxKotlin project. This would let you
choose which extensions to use based on which of the Java projects you were
using.

**Comment by maxandron** [comment]
Should I structure the folders in a similar way to how https://github.com/square/retrofit is structured?
(Put a folder named RxKotlinMath at the root of this repository?)

**Comment by MarioAriasC** [comment]
In our case RxKotlin is the project AND only module. AFAIK, and you should take it with a grain of salt, we need to have a module for RxKotlin and other for RxKotlinMath. Namely two modules in a project.

That will require deep changes on build.gradle

**Comment by thomasnield** [comment]
Maybe RxKotlinMath should be a separate project then...

**Comment by MarioAriasC** [comment]
Also I dunno how it will work with Bintray (that actually is failing at this very moment)

**Comment by MarioAriasC** [comment]
I like the idea of having several RxKotlin\* modules under ReactiveX/RxKotlin umbrella, it will promote Kotlin in general, I don't think that is impossible to sort it out just difficult.

Once we have the first one we could add more things   

Let me sort out the whole "BintrayGate" and we could think on something...

@cy6erGn0m ^^^ What do you think?

**Comment by MarioAriasC** [comment]
I sorted it out the "BintrayGate", we could start discussing this again

**Comment by JakeWharton** [comment]
Multi-modules should be relatively simple if that's the approach forward.

**Comment by maxandron** [comment]
As I see it, the pro for multi-modules is that everything is in one place (easier to find for users) and the con is that discontinuing support for the module might be more messy than in a different project.

In my opinion though, making multiple rxkotlin modules is the best way

**Comment by jakubkrolewski** [comment]
I don't think that the RxKotlin project should contain extensions to every possible RxJava\* library. Instead, RxJava\* libraries should provide Kotlin modules.
So in my opinion, this issue should be closed and an issues "Add Kotlin module" should be added to RxJavaMath.
I think this is a similar approach that @JakeWharton used for the https://github.com/JakeWharton/RxBinding library. The code in Kotlin modules is generated automatically, so maybe this is also possible for RxJavaMath.

**Comment by thomasnield** [comment]
FYI, I started an `rxkotlin-math` library. I plan on using this quite a bit so it should grow fairly quickly. 

https://github.com/thomasnield/rxkotlin-math

**Comment by stepango** [comment]
@maxandron rxKotlin not the best place for math extension. Since https://github.com/thomasnield/rxkotlin-math is out I think it's better to continue the discussion there.

**Comment by thomasnield** [comment]
@stepango @maxandron not quite out Maven-wise but will be soon!
