### ISSUE TITLE
Do these methods really belong in RxKotlin?

### ISSUE THREAD

**Issue by maxandron** [ReactiveX/RxKotlin#58]
Hi,

Just wondering about the reasoning behind adding functions such as `deferredObservable`, `observable` or `emptyObservable`.
They do not add anything kotlin specific.

They might help with readability, but do they really belong in RxKotlin?

Or am I missing something?

Thanks

**Comment by cy6erGn0m** [comment]
> They might help with readability

This is why they are here. Almost everything here is just to make code look better.

**Comment by maxandron** [comment]
I see, thanks.
I thought this library was adding kotlin specific readability helpers. These three methods could just as well be in the original RxJava api.

**Comment by JakeWharton** [comment]
> `deferredObservable`

You can already use `defer { .. }` with `import rx.Observable.defer` so :+1: to removing this.

> `emptyObservable`

You can use `empty()` with `import rx.Observable.empty` so :+1: to removing this.

> `observable`

This just seem superfluous. Almost no one should be using `create` anyway. `just`, `defer`, `fromCallable` and `fromAsync` are all better choices that will prevent you from shooting yourself in the foot. :+1: to removing this.

**Comment by ultimate-deej** [comment]
I believe these functions are here to to comply with standard Kotlin functions like `emptyArray`, `emptyMap` etc.
So they do add something kotlin specific, at least `emptyObservable`.
![empty](https://cloud.githubusercontent.com/assets/4563968/18275559/8a245ad8-7458-11e6-8add-b9e012f8ce2f.png)

**Comment by thomasnield** [comment]
I agree with @JakeWharton here. Pretty much any function that is not an extension function should be removed. These resemble more [syntactic saccharine](https://en.wikipedia.org/wiki/Syntactic_sugar#Syntactic_saccharin) than syntactic sugar. They offer minimal readability benefit and makes moving from RxJava to RxKotlin more convoluted, and many will keep using the RxJava factories anyway. 

Besides, if people want them that badly they can implement these functions themselves on their domain with little effort, to the point it is not even worth creating a library for. That's the great thing about Kotlin. You can create your own DSL for your needs. 

@stepango would you like me to put in a PR removing all these functions?

**Comment by stepango** [comment]
@thomasnield I'll prefer to deprecate it first and remove it in one of the future releases

**Comment by thomasnield** [comment]
Sounds good.

**Comment by stepango** [comment]
Agreed with @JakeWharton, @maxandron and @thomasnield. This functions will be removed in upcoming 1.x and 2.x along with some others. Feel free to reopen this issue for further discussion.
