### ISSUE TITLE
DSL for Multiple Lambda Operators?

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxKotlin#65]
I recently discovered the`subscribeWith()` operator in this project and I find it pretty elegant. 

``` kotlin
val source = Observable.just("Alpha","Beta","Gamma")

source.subscribeWith {
     onNext { println("NEXT $it") }
     onCompleted { println("DONE!") }
}
```

I wonder if we can do something similar with `Observable` operators that accept multiple lambda arguments. For example, instead of this...

``` kotlin
fun <T> Observable<T>.toImmutableList() =
        collect({ ImmutableList.builder<T>() },{ b, t -> b.add(t) })
        .map { it.build() }
```

You can explicitly specify each lambda argument

``` kotlin
fun <T> Observable<T>.toImmutableList() =
    collect { 
            stateFactory { ImmutableList.builder<T>() } 
            collector { b, t -> b.add(t) } 
    }.map { it.build() }
```

Do any of you think this is worthwhile?

**Comment by MarioAriasC** [comment]
Actually sounds quite right

**Comment by thomasnield** [comment]
Cool, would you like me to make a PR? The only disadvantage is you can't enforce all arguments to be assigned at compile time.

**Comment by thomasnield** [comment]
I'll put in PR soon. Needed to confirm this is an okay pattern before I continue porting [rxjava-extras](https://github.com/davidmoten/rxjava-extras) to [rxkotlin-extras](https://github.com/thomasnield/rxkotlin-extras). I'd prefer to follow any conventions established here.

**Comment by thomasnield** [comment]
I put in a PR. Maybe there is a way to have the generics be inferred, but I don't know how. Here is a DSL for the `collect()` operator. 

``` kotlin
import rx.Observable

fun <T,R> Observable<T>.collect(op: CollectDSL<T,R>.() -> Unit): Observable<R> {
    val collectDSL = CollectDSL<T,R>()
    op.invoke(collectDSL)
    return collect({collectDSL._stateFactory!!.invoke()}, {r,t -> collectDSL._collector!!.invoke(t,r)})
}

class CollectDSL<T,R> (
    internal var _stateFactory: (() -> R)? = null,
    internal var _collector: ((T,R) -> Unit)? = null
) {
    fun stateFactory(stateFactory: () -> R) {
        _stateFactory = stateFactory
    }
    fun collector(collector: (T,R) -> Unit) {
        _collector = collector
    }
}
```

And here is the usage. 

``` kotlin
val source = Observable.just("Alpha","Beta","Gamma","Delta")

source.collect<String,HashSet<String>> {
    stateFactory { HashSet() }
    collector { str, set -> set += str  }
}.subscribe { println(it) }
```

Unfortunately I have to specify the types for this new variant of `collect()`. Otherwise the compiler will  not be able to figure out the types. Does anybody have ideas to have the types be completely inferred? I'm not even sure if it is possible...

**Comment by thomasnield** [comment]
It would be ideal if this could be achieved. I don't know if there's some functional tricks that could be used, but I can't think of anything...

``` kotlin
val source = Observable.just("Alpha","Beta","Gamma","Delta")

source.collect {
    stateFactory { HashSet() }
    collector { str, set -> set += str  }
}.subscribe { println(it) }
```

**Comment by thomasnield** [comment]
My colleague @edvin proposed using named arguments to support inferring. I'm not sure which approach to use. Both are valid, but the latter would not be consistent with `subscribeWith()`. But it's cleaner. 

``` kotlin
    val source = Observable.just("Alpha","Beta","Gamma","Delta")

    source.collect(
        stateFactory = { HashSet() }
        collector = { str, set -> set += str  }
    ).subscribe { println(it) }
```

**Comment by thomasnield** [comment]
I think I'm going to go with the solution I posted previously by @edvin. I can't think of any cleaner way to do this. I'll continue my PR in this direction unless anybody has objections... 

``` kotlin
    val source = Observable.just("Alpha","Beta","Gamma","Delta")

    source.collect(
        stateFactory = { HashSet() }
        collector = { str, set -> set += str  }
    ).subscribe { println(it) }
```
