### ISSUE TITLE
Proposal for observableDefer() function

### ISSUE THREAD

**Issue by lenguyenthanh** [ReactiveX/RxKotlin#70]
Should we add?

```
fun <T> T.toDeferedObservable() : Observable<T> = Observable.defer { Observable.just(this) }
```

If yes, I'm happy to create a PR.

Edit: see https://github.com/ReactiveX/RxKotlin/issues/70#issuecomment-232315933

**Comment by lenguyenthanh** [comment]
It doesn't work so I close this.

**Comment by MarioAriasC** [comment]
Try with a non extension function, maybe it could work, something like

``` kotlin
observableDefer(x)
```

**Comment by lenguyenthanh** [comment]
```
fun<T> observableDefer(x: T) = Observable.defer { Observable.just(x) }
```

Does it look good?

**Comment by MarioAriasC** [comment]
You'll need an explicit return type

**Comment by lenguyenthanh** [comment]
Thanks, I'll create a PR for this one.
