### ISSUE TITLE
Add completable method wrapping Completable.create

### ISSUE THREAD

**Issue by dynaxis** [ReactiveX/RxKotlin#76]
Why no `completable` method that is comparable to `single` or `observable` which takes a closure with a subscriber as its sole argument? To wrap an async Java API based on listener, I needed it and workarounded by invoking `Completable.create` directly.

**Comment by ralph-bergmann** [comment]
https://github.com/ReactiveX/RxKotlin/pull/74

**Comment by stepango** [comment]
Closing, check https://github.com/ReactiveX/RxKotlin/issues/58 for details
