### ISSUE TITLE
Math/Statistical Extension Functions

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxKotlin#88]
It might be helpful to create math/statistical reducing extension functions like so...

```kotlin
import rx.Observable
import java.math.BigDecimal

fun Observable<Int>.sumInt() = reduce {total, next -> total + next }
fun Observable<Long>.sumLong() = reduce {total, next -> total + next }
fun Observable<BigDecimal>.sumBigDecimal() = reduce(BigDecimal.ZERO) { total, next -> total + next }

fun Observable<Int>.minInt() = reduce {min, next -> if (min > next) next else min }
fun Observable<Long>.minLong() = reduce {min, next -> if (min > next) next else min }
fun Observable<BigDecimal>.minBigDecimal() = reduce { min, next -> if (min > next) next else min }

fun Observable<Int>.maxInt() = reduce {min, next -> if (min < next) next else min }
fun Observable<Long>.maxLong() = reduce {min, next -> if (min < next) next else min }
fun Observable<BigDecimal>.maxBigDecimal() = reduce { min, next -> if (min < next) next else min }

fun Observable<Int>.averageInt() = this.publish().autoConnect(2).let {
    Observable.zip(it.sumInt(), it.count()) { sum, count -> sum / count }
}
// and so on...
```

Of course, it might be better to split extension functions for `Int`, `Double`, Long`, `Float`, and `BigDecimal` in separate files so we can call all of them `sum()` instead of `sumLong()`, and usage would explicitly import the ones we want. 

Thoughts?

**Comment by JakeWharton** [comment]
The scope of the library is already ill-defined. I would prefer those to be in a separate artifact than the core language adapter because there's no real bound on the number of mathematical functions that one could write. Just like we see now with people contributing any and all extension methods that have _anything_ to do with the Rx it seems like the number would just grow and grow.

**Comment by thomasnield** [comment]
Make sense. I'll start a separate library.

**Comment by thomasnield** [comment]
I started putting a library together. https://github.com/thomasnield/rxkotlin-math
