### ISSUE TITLE
1.x Release Candidate Prep

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxKotlin#92]
@stepango I think I'm going to try and do a a "release candidate" for 1.x, and see if it deploys to Maven Central. Is it okay to move forward?

**Comment by thomasnield** [comment]
After I make those style changes in my last commit, of course, when I get home.

**Comment by stepango** [comment]
Thanks, @thomasnield. Sure, go ahead.

**Comment by stepango** [comment]
Updated readme a little bit https://github.com/ReactiveX/RxKotlin/pull/93

**Comment by thomasnield** [comment]
I tried to do a deployment but it does not seem to be triggering on a GitHub release. 

https://repo1.maven.org/maven2/io/reactivex/rxkotlin/

I updated the README with instructions on how to do a JitPack build with Gradle/Maven. But we will need to figure out what is going wrong before we officially release 1.0.
